import { db } from "@/lib/db";
import { homepage } from "@/db/schema";
import { successResponse, errorResponse } from "@/lib/api-response";

// GET /api/admin/homepage - Get homepage content
export async function GET() {
    try {
        const homepageContent = await db.select().from(homepage).limit(1).then((res) => res[0]);

        // If no homepage content exists, create default one
        if (!homepageContent) {
            const defaultHomepage = await db
                .insert(homepage)
                .values({
                    heroSmallLabelEn: "",
                    heroSmallLabelDe: "",
                    heroTitleEn: "",
                    heroTitleDe: "",
                    heroDescriptionEn: "",
                    heroDescriptionDe: "",
                    heroShortDescriptionEn: "",
                    heroShortDescriptionDe: "",
                    heroInputPlaceholderEn: "",
                    heroInputPlaceholderDe: "",
                    heroPrimaryButtonEn: "",
                    heroPrimaryButtonDe: "",
                    heroSecondaryButtonEn: "",
                    heroSecondaryButtonDe: "",
                    heroHotlineCtaEn: "",
                    heroHotlineCtaDe: "",
                    heroRequestButtonEn: "",
                    heroRequestButtonDe: "",
                    valueBlocksTitleEn: "",
                    valueBlocksTitleDe: "",
                    valueBlocksSubtitleEn: "",
                    valueBlocksSubtitleDe: "",
                    valueBlock1TitleEn: "",
                    valueBlock1TitleDe: "",
                    valueBlock1DescriptionEn: "",
                    valueBlock1DescriptionDe: "",
                    valueBlock2TitleEn: "",
                    valueBlock2TitleDe: "",
                    valueBlock2DescriptionEn: "",
                    valueBlock2DescriptionDe: "",
                    valueBlock3TitleEn: "",
                    valueBlock3TitleDe: "",
                    valueBlock3DescriptionEn: "",
                    valueBlock3DescriptionDe: "",
                    valueBlock4TitleEn: "",
                    valueBlock4TitleDe: "",
                    valueBlock4DescriptionEn: "",
                    valueBlock4DescriptionDe: "",
                    howItWorksTitleEn: "",
                    howItWorksTitleDe: "",
                    howItWorksSubtitleEn: "",
                    howItWorksSubtitleDe: "",
                    step1TitleEn: "",
                    step1TitleDe: "",
                    step1Description1En: "",
                    step1Description1De: "",
                    step1Description2En: "",
                    step1Description2De: "",
                    step2TitleEn: "",
                    step2TitleDe: "",
                    step2Description1En: "",
                    step2Description1De: "",
                    step2Description2En: "",
                    step2Description2De: "",
                    step3TitleEn: "",
                    step3TitleDe: "",
                    step3Description1En: "",
                    step3Description1De: "",
                    step3Description2En: "",
                    step3Description2De: "",
                    step4TitleEn: "",
                    step4TitleDe: "",
                    step4Description1En: "",
                    step4Description1De: "",
                    step4Description2En: "",
                    step4Description2De: "",
                    step5TitleEn: "",
                    step5TitleDe: "",
                    step5Description1En: "",
                    step5Description1De: "",
                    step5Description2En: "",
                    step5Description2De: "",
                    ctaCardButton1En: "",
                    ctaCardButton1De: "",
                    ctaCardButton2En: "",
                    ctaCardButton2De: "",
                    faqTitleEn: "",
                    faqTitleDe: "",
                    faqSubtitleEn: "",
                    faqSubtitleDe: "",
                    partnersTitleEn: "",
                    partnersTitleDe: "",
                    partnersSubtitleEn: "",
                    partnersSubtitleDe: "",
                })
                .returning();

            return successResponse("Homepage content fetched successfully", defaultHomepage[0]);
        }

        return successResponse("Homepage content fetched successfully", homepageContent);
    } catch (error) {
        return errorResponse(error.message || "Failed to fetch homepage content");
    }
}

// PUT /api/admin/homepage - Update homepage content
export async function PUT(req) {
    try {
        const body = await req.json();
        const {
            heroSmallLabelEn,
            heroSmallLabelDe,
            heroTitleEn,
            heroTitleDe,
            heroDescriptionEn,
            heroDescriptionDe,
            heroShortDescriptionEn,
            heroShortDescriptionDe,
            heroInputPlaceholderEn,
            heroInputPlaceholderDe,
            heroPrimaryButtonEn,
            heroPrimaryButtonDe,
            heroSecondaryButtonEn,
            heroSecondaryButtonDe,
            heroHotlineCtaEn,
            heroHotlineCtaDe,
            heroRequestButtonEn,
            heroRequestButtonDe,
            valueBlocksTitleEn,
            valueBlocksTitleDe,
            valueBlocksSubtitleEn,
            valueBlocksSubtitleDe,
            valueBlock1TitleEn,
            valueBlock1TitleDe,
            valueBlock1DescriptionEn,
            valueBlock1DescriptionDe,
            valueBlock2TitleEn,
            valueBlock2TitleDe,
            valueBlock2DescriptionEn,
            valueBlock2DescriptionDe,
            valueBlock3TitleEn,
            valueBlock3TitleDe,
            valueBlock3DescriptionEn,
            valueBlock3DescriptionDe,
            valueBlock4TitleEn,
            valueBlock4TitleDe,
            valueBlock4DescriptionEn,
            valueBlock4DescriptionDe,
            howItWorksTitleEn,
            howItWorksTitleDe,
            howItWorksSubtitleEn,
            howItWorksSubtitleDe,
            step1TitleEn,
            step1TitleDe,
            step1Description1En,
            step1Description1De,
            step1Description2En,
            step1Description2De,
            step2TitleEn,
            step2TitleDe,
            step2Description1En,
            step2Description1De,
            step2Description2En,
            step2Description2De,
            step3TitleEn,
            step3TitleDe,
            step3Description1En,
            step3Description1De,
            step3Description2En,
            step3Description2De,
            step4TitleEn,
            step4TitleDe,
            step4Description1En,
            step4Description1De,
            step4Description2En,
            step4Description2De,
            step5TitleEn,
            step5TitleDe,
            step5Description1En,
            step5Description1De,
            step5Description2En,
            step5Description2De,
            ctaCardButton1En,
            ctaCardButton1De,
            ctaCardButton2En,
            ctaCardButton2De,
            faqTitleEn,
            faqTitleDe,
            faqSubtitleEn,
            faqSubtitleDe,
            partnersTitleEn,
            partnersTitleDe,
            partnersSubtitleEn,
            partnersSubtitleDe,
        } = body;

        // Get existing homepage or create new one
        const existing = await db.select().from(homepage).limit(1).then((res) => res[0]);

        let result;
        if (existing) {
            // Update existing
            result = await db
                .update(homepage)
                .set({
                    heroSmallLabelEn: heroSmallLabelEn || "",
                    heroSmallLabelDe: heroSmallLabelDe || "",
                    heroTitleEn: heroTitleEn || "",
                    heroTitleDe: heroTitleDe || "",
                    heroDescriptionEn: heroDescriptionEn || "",
                    heroDescriptionDe: heroDescriptionDe || "",
                    heroShortDescriptionEn: heroShortDescriptionEn || "",
                    heroShortDescriptionDe: heroShortDescriptionDe || "",
                    heroInputPlaceholderEn: heroInputPlaceholderEn || "",
                    heroInputPlaceholderDe: heroInputPlaceholderDe || "",
                    heroPrimaryButtonEn: heroPrimaryButtonEn || "",
                    heroPrimaryButtonDe: heroPrimaryButtonDe || "",
                    heroSecondaryButtonEn: heroSecondaryButtonEn || "",
                    heroSecondaryButtonDe: heroSecondaryButtonDe || "",
                    heroHotlineCtaEn: heroHotlineCtaEn || "",
                    heroHotlineCtaDe: heroHotlineCtaDe || "",
                    heroRequestButtonEn: heroRequestButtonEn || "",
                    heroRequestButtonDe: heroRequestButtonDe || "",
                    valueBlocksTitleEn: valueBlocksTitleEn || "",
                    valueBlocksTitleDe: valueBlocksTitleDe || "",
                    valueBlocksSubtitleEn: valueBlocksSubtitleEn || "",
                    valueBlocksSubtitleDe: valueBlocksSubtitleDe || "",
                    valueBlock1TitleEn: valueBlock1TitleEn || "",
                    valueBlock1TitleDe: valueBlock1TitleDe || "",
                    valueBlock1DescriptionEn: valueBlock1DescriptionEn || "",
                    valueBlock1DescriptionDe: valueBlock1DescriptionDe || "",
                    valueBlock2TitleEn: valueBlock2TitleEn || "",
                    valueBlock2TitleDe: valueBlock2TitleDe || "",
                    valueBlock2DescriptionEn: valueBlock2DescriptionEn || "",
                    valueBlock2DescriptionDe: valueBlock2DescriptionDe || "",
                    valueBlock3TitleEn: valueBlock3TitleEn || "",
                    valueBlock3TitleDe: valueBlock3TitleDe || "",
                    valueBlock3DescriptionEn: valueBlock3DescriptionEn || "",
                    valueBlock3DescriptionDe: valueBlock3DescriptionDe || "",
                    valueBlock4TitleEn: valueBlock4TitleEn || "",
                    valueBlock4TitleDe: valueBlock4TitleDe || "",
                    valueBlock4DescriptionEn: valueBlock4DescriptionEn || "",
                    valueBlock4DescriptionDe: valueBlock4DescriptionDe || "",
                    howItWorksTitleEn: howItWorksTitleEn || "",
                    howItWorksTitleDe: howItWorksTitleDe || "",
                    howItWorksSubtitleEn: howItWorksSubtitleEn || "",
                    howItWorksSubtitleDe: howItWorksSubtitleDe || "",
                    step1TitleEn: step1TitleEn || "",
                    step1TitleDe: step1TitleDe || "",
                    step1Description1En: step1Description1En || "",
                    step1Description1De: step1Description1De || "",
                    step1Description2En: step1Description2En || "",
                    step1Description2De: step1Description2De || "",
                    step2TitleEn: step2TitleEn || "",
                    step2TitleDe: step2TitleDe || "",
                    step2Description1En: step2Description1En || "",
                    step2Description1De: step2Description1De || "",
                    step2Description2En: step2Description2En || "",
                    step2Description2De: step2Description2De || "",
                    step3TitleEn: step3TitleEn || "",
                    step3TitleDe: step3TitleDe || "",
                    step3Description1En: step3Description1En || "",
                    step3Description1De: step3Description1De || "",
                    step3Description2En: step3Description2En || "",
                    step3Description2De: step3Description2De || "",
                    step4TitleEn: step4TitleEn || "",
                    step4TitleDe: step4TitleDe || "",
                    step4Description1En: step4Description1En || "",
                    step4Description1De: step4Description1De || "",
                    step4Description2En: step4Description2En || "",
                    step4Description2De: step4Description2De || "",
                    step5TitleEn: step5TitleEn || "",
                    step5TitleDe: step5TitleDe || "",
                    step5Description1En: step5Description1En || "",
                    step5Description1De: step5Description1De || "",
                    step5Description2En: step5Description2En || "",
                    step5Description2De: step5Description2De || "",
                    ctaCardButton1En: ctaCardButton1En || "",
                    ctaCardButton1De: ctaCardButton1De || "",
                    ctaCardButton2En: ctaCardButton2En || "",
                    ctaCardButton2De: ctaCardButton2De || "",
                    faqTitleEn: faqTitleEn || "",
                    faqTitleDe: faqTitleDe || "",
                    faqSubtitleEn: faqSubtitleEn || "",
                    faqSubtitleDe: faqSubtitleDe || "",
                    partnersTitleEn: partnersTitleEn || "",
                    partnersTitleDe: partnersTitleDe || "",
                    partnersSubtitleEn: partnersSubtitleEn || "",
                    partnersSubtitleDe: partnersSubtitleDe || "",
                    updatedAt: new Date(),
                })
                .returning();
        } else {
            // Create new
            result = await db
                .insert(homepage)
                .values({
                    heroSmallLabelEn: heroSmallLabelEn || "",
                    heroSmallLabelDe: heroSmallLabelDe || "",
                    heroTitleEn: heroTitleEn || "",
                    heroTitleDe: heroTitleDe || "",
                    heroDescriptionEn: heroDescriptionEn || "",
                    heroDescriptionDe: heroDescriptionDe || "",
                    heroShortDescriptionEn: heroShortDescriptionEn || "",
                    heroShortDescriptionDe: heroShortDescriptionDe || "",
                    heroInputPlaceholderEn: heroInputPlaceholderEn || "",
                    heroInputPlaceholderDe: heroInputPlaceholderDe || "",
                    heroPrimaryButtonEn: heroPrimaryButtonEn || "",
                    heroPrimaryButtonDe: heroPrimaryButtonDe || "",
                    heroSecondaryButtonEn: heroSecondaryButtonEn || "",
                    heroSecondaryButtonDe: heroSecondaryButtonDe || "",
                    heroHotlineCtaEn: heroHotlineCtaEn || "",
                    heroHotlineCtaDe: heroHotlineCtaDe || "",
                    heroRequestButtonEn: heroRequestButtonEn || "",
                    heroRequestButtonDe: heroRequestButtonDe || "",
                    valueBlocksTitleEn: valueBlocksTitleEn || "",
                    valueBlocksTitleDe: valueBlocksTitleDe || "",
                    valueBlocksSubtitleEn: valueBlocksSubtitleEn || "",
                    valueBlocksSubtitleDe: valueBlocksSubtitleDe || "",
                    valueBlock1TitleEn: valueBlock1TitleEn || "",
                    valueBlock1TitleDe: valueBlock1TitleDe || "",
                    valueBlock1DescriptionEn: valueBlock1DescriptionEn || "",
                    valueBlock1DescriptionDe: valueBlock1DescriptionDe || "",
                    valueBlock2TitleEn: valueBlock2TitleEn || "",
                    valueBlock2TitleDe: valueBlock2TitleDe || "",
                    valueBlock2DescriptionEn: valueBlock2DescriptionEn || "",
                    valueBlock2DescriptionDe: valueBlock2DescriptionDe || "",
                    valueBlock3TitleEn: valueBlock3TitleEn || "",
                    valueBlock3TitleDe: valueBlock3TitleDe || "",
                    valueBlock3DescriptionEn: valueBlock3DescriptionEn || "",
                    valueBlock3DescriptionDe: valueBlock3DescriptionDe || "",
                    valueBlock4TitleEn: valueBlock4TitleEn || "",
                    valueBlock4TitleDe: valueBlock4TitleDe || "",
                    valueBlock4DescriptionEn: valueBlock4DescriptionEn || "",
                    valueBlock4DescriptionDe: valueBlock4DescriptionDe || "",
                    howItWorksTitleEn: howItWorksTitleEn || "",
                    howItWorksTitleDe: howItWorksTitleDe || "",
                    howItWorksSubtitleEn: howItWorksSubtitleEn || "",
                    howItWorksSubtitleDe: howItWorksSubtitleDe || "",
                    step1TitleEn: step1TitleEn || "",
                    step1TitleDe: step1TitleDe || "",
                    step1Description1En: step1Description1En || "",
                    step1Description1De: step1Description1De || "",
                    step1Description2En: step1Description2En || "",
                    step1Description2De: step1Description2De || "",
                    step2TitleEn: step2TitleEn || "",
                    step2TitleDe: step2TitleDe || "",
                    step2Description1En: step2Description1En || "",
                    step2Description1De: step2Description1De || "",
                    step2Description2En: step2Description2En || "",
                    step2Description2De: step2Description2De || "",
                    step3TitleEn: step3TitleEn || "",
                    step3TitleDe: step3TitleDe || "",
                    step3Description1En: step3Description1En || "",
                    step3Description1De: step3Description1De || "",
                    step3Description2En: step3Description2En || "",
                    step3Description2De: step3Description2De || "",
                    step4TitleEn: step4TitleEn || "",
                    step4TitleDe: step4TitleDe || "",
                    step4Description1En: step4Description1En || "",
                    step4Description1De: step4Description1De || "",
                    step4Description2En: step4Description2En || "",
                    step4Description2De: step4Description2De || "",
                    step5TitleEn: step5TitleEn || "",
                    step5TitleDe: step5TitleDe || "",
                    step5Description1En: step5Description1En || "",
                    step5Description1De: step5Description1De || "",
                    step5Description2En: step5Description2En || "",
                    step5Description2De: step5Description2De || "",
                    ctaCardButton1En: ctaCardButton1En || "",
                    ctaCardButton1De: ctaCardButton1De || "",
                    ctaCardButton2En: ctaCardButton2En || "",
                    ctaCardButton2De: ctaCardButton2De || "",
                    faqTitleEn: faqTitleEn || "",
                    faqTitleDe: faqTitleDe || "",
                    faqSubtitleEn: faqSubtitleEn || "",
                    faqSubtitleDe: faqSubtitleDe || "",
                    partnersTitleEn: partnersTitleEn || "",
                    partnersTitleDe: partnersTitleDe || "",
                    partnersSubtitleEn: partnersSubtitleEn || "",
                    partnersSubtitleDe: partnersSubtitleDe || "",
                })
                .returning();
        }

        return successResponse("Homepage content updated successfully", result[0]);
    } catch (error) {
        return errorResponse(error.message || "Failed to update homepage content");
    }
}


