import { pgTable, uuid, text, timestamp } from "drizzle-orm/pg-core";

export const homepage = pgTable("homepage", {
    id: uuid("id").defaultRandom().primaryKey(),
    // Hero Section - Section 1
    heroSmallLabelEn: text("hero_small_label_en").notNull().default(""),
    heroSmallLabelDe: text("hero_small_label_de").notNull().default(""),
    heroTitleEn: text("hero_title_en").notNull().default(""),
    heroTitleDe: text("hero_title_de").notNull().default(""),
    heroDescriptionEn: text("hero_description_en").notNull().default(""),
    heroDescriptionDe: text("hero_description_de").notNull().default(""),
    heroShortDescriptionEn: text("hero_short_description_en").notNull().default(""),
    heroShortDescriptionDe: text("hero_short_description_de").notNull().default(""),
    heroInputPlaceholderEn: text("hero_input_placeholder_en").notNull().default(""),
    heroInputPlaceholderDe: text("hero_input_placeholder_de").notNull().default(""),
    heroPrimaryButtonEn: text("hero_primary_button_en").notNull().default(""),
    heroPrimaryButtonDe: text("hero_primary_button_de").notNull().default(""),
    heroSecondaryButtonEn: text("hero_secondary_button_en").notNull().default(""),
    heroSecondaryButtonDe: text("hero_secondary_button_de").notNull().default(""),
    heroHotlineCtaEn: text("hero_hotline_cta_en").notNull().default(""),
    heroHotlineCtaDe: text("hero_hotline_cta_de").notNull().default(""),
    heroRequestButtonEn: text("hero_request_button_en").notNull().default(""),
    heroRequestButtonDe: text("hero_request_button_de").notNull().default(""),
    // Value Blocks Section - Section 2
    valueBlocksTitleEn: text("value_blocks_title_en").notNull().default(""),
    valueBlocksTitleDe: text("value_blocks_title_de").notNull().default(""),
    valueBlocksSubtitleEn: text("value_blocks_subtitle_en").notNull().default(""),
    valueBlocksSubtitleDe: text("value_blocks_subtitle_de").notNull().default(""),
    valueBlock1TitleEn: text("value_block_1_title_en").notNull().default(""),
    valueBlock1TitleDe: text("value_block_1_title_de").notNull().default(""),
    valueBlock1DescriptionEn: text("value_block_1_description_en").notNull().default(""),
    valueBlock1DescriptionDe: text("value_block_1_description_de").notNull().default(""),
    valueBlock2TitleEn: text("value_block_2_title_en").notNull().default(""),
    valueBlock2TitleDe: text("value_block_2_title_de").notNull().default(""),
    valueBlock2DescriptionEn: text("value_block_2_description_en").notNull().default(""),
    valueBlock2DescriptionDe: text("value_block_2_description_de").notNull().default(""),
    valueBlock3TitleEn: text("value_block_3_title_en").notNull().default(""),
    valueBlock3TitleDe: text("value_block_3_title_de").notNull().default(""),
    valueBlock3DescriptionEn: text("value_block_3_description_en").notNull().default(""),
    valueBlock3DescriptionDe: text("value_block_3_description_de").notNull().default(""),
    valueBlock4TitleEn: text("value_block_4_title_en").notNull().default(""),
    valueBlock4TitleDe: text("value_block_4_title_de").notNull().default(""),
    valueBlock4DescriptionEn: text("value_block_4_description_en").notNull().default(""),
    valueBlock4DescriptionDe: text("value_block_4_description_de").notNull().default(""),
    // How It Works Section - Section 3
    howItWorksTitleEn: text("how_it_works_title_en").notNull().default(""),
    howItWorksTitleDe: text("how_it_works_title_de").notNull().default(""),
    howItWorksSubtitleEn: text("how_it_works_subtitle_en").notNull().default(""),
    howItWorksSubtitleDe: text("how_it_works_subtitle_de").notNull().default(""),
    // Step 1
    step1TitleEn: text("step_1_title_en").notNull().default(""),
    step1TitleDe: text("step_1_title_de").notNull().default(""),
    step1Description1En: text("step_1_description_1_en").notNull().default(""),
    step1Description1De: text("step_1_description_1_de").notNull().default(""),
    step1Description2En: text("step_1_description_2_en").notNull().default(""),
    step1Description2De: text("step_1_description_2_de").notNull().default(""),
    // Step 2
    step2TitleEn: text("step_2_title_en").notNull().default(""),
    step2TitleDe: text("step_2_title_de").notNull().default(""),
    step2Description1En: text("step_2_description_1_en").notNull().default(""),
    step2Description1De: text("step_2_description_1_de").notNull().default(""),
    step2Description2En: text("step_2_description_2_en").notNull().default(""),
    step2Description2De: text("step_2_description_2_de").notNull().default(""),
    // Step 3
    step3TitleEn: text("step_3_title_en").notNull().default(""),
    step3TitleDe: text("step_3_title_de").notNull().default(""),
    step3Description1En: text("step_3_description_1_en").notNull().default(""),
    step3Description1De: text("step_3_description_1_de").notNull().default(""),
    step3Description2En: text("step_3_description_2_en").notNull().default(""),
    step3Description2De: text("step_3_description_2_de").notNull().default(""),
    // Step 4
    step4TitleEn: text("step_4_title_en").notNull().default(""),
    step4TitleDe: text("step_4_title_de").notNull().default(""),
    step4Description1En: text("step_4_description_1_en").notNull().default(""),
    step4Description1De: text("step_4_description_1_de").notNull().default(""),
    step4Description2En: text("step_4_description_2_en").notNull().default(""),
    step4Description2De: text("step_4_description_2_de").notNull().default(""),
    // Step 5
    step5TitleEn: text("step_5_title_en").notNull().default(""),
    step5TitleDe: text("step_5_title_de").notNull().default(""),
    step5Description1En: text("step_5_description_1_en").notNull().default(""),
    step5Description1De: text("step_5_description_1_de").notNull().default(""),
    step5Description2En: text("step_5_description_2_en").notNull().default(""),
    step5Description2De: text("step_5_description_2_de").notNull().default(""),
    // CTA Card
    ctaCardButton1En: text("cta_card_button_1_en").notNull().default(""),
    ctaCardButton1De: text("cta_card_button_1_de").notNull().default(""),
    ctaCardButton2En: text("cta_card_button_2_en").notNull().default(""),
    ctaCardButton2De: text("cta_card_button_2_de").notNull().default(""),
    // FAQ Section - Section 4
    faqTitleEn: text("faq_title_en").notNull().default(""),
    faqTitleDe: text("faq_title_de").notNull().default(""),
    faqSubtitleEn: text("faq_subtitle_en").notNull().default(""),
    faqSubtitleDe: text("faq_subtitle_de").notNull().default(""),
    // Partners Section - Section 5
    partnersTitleEn: text("partners_title_en").notNull().default(""),
    partnersTitleDe: text("partners_title_de").notNull().default(""),
    partnersSubtitleEn: text("partners_subtitle_en").notNull().default(""),
    partnersSubtitleDe: text("partners_subtitle_de").notNull().default(""),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
});


